[package]
name = "datafusion-optimal-plans"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "50"
arrow = "56"
tokio = { version = "1.46", features = ["full"] }

[dev-dependencies]
insta = { version = "1.43", features = ["filters"] }

